/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

package outsystems.hubedition.extensibility.data.configurationservice.metaconfiguration;

import java.text.*;
import java.util.*;
import outsystems.hubedition.extensibility.data.*;
import outsystems.hubedition.extensibility.data.configurationservice.*;
import outsystems.hubedition.util.*;
import outsystems.hubedition.util.delegates.*;
import java.math.BigDecimal;
import outsystems.hubedition.extensibility.data.configurationservice.AdvancedConfiguration;
import outsystems.hubedition.extensibility.data.configurationservice.IIntegrationDatabaseConfiguration;
import outsystems.hubedition.extensibility.data.configurationservice.ParameterRegion;


public class ConnStringTemplateParam implements IUserDefinedParameter {
    public static final TypeInformation<ConnStringTemplateParam> TypeInfo = TypeInformation.get(ConnStringTemplateParam.class);
    private IIntegrationDatabaseConfiguration configuration;
    
    public ConnStringTemplateParam(IIntegrationDatabaseConfiguration configuration){
        this.configuration = configuration;
    }
    
    public final boolean isVisible()
    {
        return !StringUtils.isNullOrEmpty(getAutoCompleteExpression());
    }
    
    public final String getLabel()
    {
        return "Connection String";
    }
    
    public final String getExample()
    {
        return "";
    }
    
    public final boolean isMandatory()
    {
        return false;
    }
    
    public final int getOrder()
    {
        return 2;
    }
    
    public final EnumSet<ParameterRegion> getRegion()
    {
        return EnumSet.of(ParameterRegion.Advanced);
    }
    
    public final boolean isPassword()
    {
        return false;
    }
    
    
    public final Class<?> getType()
    {
        return String.class;
    }
    
    public final String getName()
    {
        return "ConnectionStringTemplateExpression";
    }
    
    public final void set(String value) {
        
    }
    
    public final String get() {
        return getAutoCompleteExpression();
    }
    
    public final boolean isReadOnly()
    {
        return true;
    }
    
    public final boolean isMultiline()
    {
        return false;
    }
    
    public final String getAutoCompleteExpression()
    {
        return configuration.getAdvancedConfiguration().getConnectionStringTemplateExpression();
    }
    
    
    public final boolean isEncrypt()
    {
        return false;
    }
    
    public final boolean isPersist()
    {
        return false;
    }
}
