/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using OutSystems.RuntimeCommon;

namespace OutSystems.HubEdition.Extensibility.Data.Platform.Session {

    public static class SessionConstants {

        internal const int APP_SUFFIX_LENGTH = 8;

        public static readonly int ID_LENGTH = 80 /* From: SessionIDManager.SessionIDMaxLength */ + APP_SUFFIX_LENGTH;

        public static readonly int STORE_STR_MAX = 280;

        public static readonly int VARIABLE_NAME_LENGTH = 50;

    }
}
