/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

package outsystems.hubedition.extensibility.data.transactionservice;

import java.text.*;
import java.util.*;
import outsystems.hubedition.extensibility.data.*;
import outsystems.hubedition.util.*;
import outsystems.hubedition.util.delegates.*;
import outsystems.runtimecommon.*;
import java.math.BigDecimal;


/**
 *	Exception raised when it&#39;s not possible to commit or rollback a transaction. Check the message to see the reason of the exception.
 */
public class InvalidCommitOrRollbackTransactionException extends TransactionException {
    public static final TypeInformation<InvalidCommitOrRollbackTransactionException> TypeInfo = TypeInformation.get(InvalidCommitOrRollbackTransactionException.class);
    public InvalidCommitOrRollbackTransactionException(String message){
        super(message);
    }
}
