/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using OutSystems.RuntimeCommon;

namespace OutSystems.HubEdition.Extensibility.Data.ConfigurationService {
    
    /// <summary>
    /// Attribute used to identify configuration parameters. 
    /// This attribute should be used in a database configuration objects.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property)]
    public class ConfigurationParameter: Attribute {

        /// <summary>
        /// Defines if the attribute should be encrypted
        /// </summary>
        public bool Encrypt {
            get;
            set;
        }


        private bool persist = true;
        /// <summary>
        /// Defines if this parameter should be persisted
        /// </summary>
        public bool Persist {
            get { return persist; }
            set { persist = value; }
        }

    }
}