/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

package outsystems.hubedition.extensibility.data.configurationservice;

import java.text.*;
import java.util.*;
import outsystems.hubedition.extensibility.data.*;
import outsystems.hubedition.util.*;
import outsystems.hubedition.util.delegates.*;
import java.math.BigDecimal;
import outsystems.hubedition.extensibility.data.IDatabaseProvider;


/**
 *	Encapsulates a connection string and other configuration information required to connect to a database.
 */
public interface IIntegrationDatabaseConfiguration
{
    
    /**
	 *	Gets the database provider. It provides information about the database, and access to its services.
	 *	@return	The database provider.
	 */
    public IDatabaseProvider getDatabaseProvider();
    
    /**
	 *	Gets the connection string that allows connecting to a database.
	 *	@return	The connection string.
	 */
    public String getConnectionString();
    
    /**
	 *	Gets the database identifier to be used in the configuration.
	 *	@return	The database identifier.
	 */
    public String getDatabaseIdentifier();
    
    /**
	 *	Gets the advanced configuration object that allows users to set connection parameters in an advanced way.
	 *	@return	The advanced configuration object.
	 */
    public AdvancedConfiguration getAdvancedConfiguration();
    
    /**
	 *	Gets the connection string that overrides specified configuration parameter values.
	 *	@return	The connection string.
	 */
    public String getConnectionStringOverride();
    
    /**
	 *	Gets the connection string that overrides specified configuration parameter values.
	 *	@param	value	The connection string.
	 */
    public void setConnectionStringOverride(String value);
    
    /**
	 *	Gets the object that compacts all the needed configuration parameters to be used in runtime.
	 *	@return	The runtime database configuration.
	 */
    public IRuntimeDatabaseConfiguration getRuntimeDatabaseConfiguration();
}
