/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using NUnit.Framework;
using NUnitExtension.OutSystems.Framework;
using OutSystems.RuntimeCommon;

namespace OutSystems.ServerTests.DatabaseProvider.Framework {

    public abstract class DashboardTest : IDashboardTestFixture {

        public const string DashboardTestKind =
            
            "UnitTest.HubServer";

        [TestFixtureSetUp]
        public virtual void InitFixture() {
        }

        [TestFixtureTearDown]
        public virtual void DisposeFixture() {
        }

        [SetUp]
        public virtual void SetUp() {
        }

        [TearDown]
        public virtual void TearDown() {
        }

        private IDashboardSession _dashboard;

        public IDashboardSession dashboard {
            get {
#if DUMMY_DASHBOARD
                // Allow developers to debug inside VisualStudio2012
                if (System.Diagnostics.Debugger.IsAttached) {
                    if (_dashboard == null) {
                        _dashboard = new DummyDebuggerDashboard();
                    }
                }
#endif
                return _dashboard;
            }
            set { _dashboard = value; }
        }
    }
}