/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System.Collections.Generic;
using OutSystems.HubEdition.Extensibility.Data;
using OutSystems.HubEdition.Extensibility.Data.ConfigurationService;

namespace OutSystems.ServerTests.DatabaseProvider.Framework {
    public interface IDatabaseProviderTestCase<TDatabaseProvider> where TDatabaseProvider: IDatabaseProvider {
        string Name { get; set; }        
        void InitializeServices(TDatabaseProvider provider, IRuntimeDatabaseConfiguration runtimeConfiguration, IRuntimeDatabaseConfiguration bootstrapConfiguration, bool runWithBootstrapUser);
        IEnumerable<string> BootstrapScripts { get; set; }
        IEnumerable<string> TeardownScripts { get; set; }
        void ExecuteTeardown();
        void ExecuteBootstrap();
        bool ExecuteScriptsWithoutTransaction { get; set; }
    }
}
