/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

package outsystems.hubedition.extensibility.data.platform;

import java.text.*;
import java.util.*;
import outsystems.hubedition.extensibility.data.*;
import outsystems.hubedition.util.*;
import outsystems.hubedition.util.delegates.*;
import java.math.BigDecimal;
import outsystems.hubedition.extensibility.data.IProviderProperties;


/**
 *	Represents a set of properties that are specific to a platform database provider.
 */
public interface IPlatformProviderProperties extends IProviderProperties
{
    
    /**
	 *	Returns true if the Multiple Database feature is supported for this provider.
	 *	@return	True if Multiple Database feature is supported, False otherwise.
	 */
    public boolean isSupportsMultipleDatabases();
    
}
