/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

package outsystems.hubedition.extensibility.data.platform.configuration;

class NameSuggestor implements ISuggestor{

	private String suggestionPrefix;
	private String suggestionSuffix;
	private boolean suggestLowerCase;

	public NameSuggestor(String userInput, String searchFor){
		if (!hasSuggestion(userInput, searchFor)) {
			throw new IllegalArgumentException();
		}

		inferSuggestion(userInput, searchFor);
	}

	public static boolean hasSuggestion(String userInput, String searchFor){
		int startIndex=userInput.toUpperCase().indexOf(searchFor.toUpperCase());

		return startIndex>=0;
	}

	private void inferSuggestion(String userInput, String searchFor){

		int startIndex=userInput.toUpperCase().indexOf(searchFor.toUpperCase());

		suggestionPrefix=userInput.substring(0, startIndex);
		suggestionSuffix=userInput.substring(startIndex+searchFor.length(),userInput.length());
		//If it's not lowerCase, we'll suggest UpperCase anyway (Even if not all characters are Upper Cased)
		suggestLowerCase=userInput.indexOf(searchFor.toLowerCase())>=0;
	}

	@Override
	public String getSuggestion(String seed, String defaultValue){

		if (suggestLowerCase){
			return suggestionPrefix+seed.toLowerCase()+suggestionSuffix;
		}else{
			return suggestionPrefix+seed.toUpperCase()+suggestionSuffix;
		}
	}
}
