/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

package outsystems.hubedition.extensibility.data.platform.configuration;

public class NameSuggestorFactory {

	private NameSuggestorFactory(){}

	public static ISuggestor newSuggestor(boolean tryUseSuggestions, String userInput, String searchFor){

		if (tryUseSuggestions && NameSuggestor.hasSuggestion(userInput, searchFor)) {
			return new NameSuggestor(userInput, searchFor);
		} else {
			return new DefaultNameSuggestor();
		}
	}
}
