/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using OutSystems.HubEdition.Extensibility.Data.ConfigurationService;
using OutSystems.HubEdition.Extensibility.Data.Platform.Configuration;
using OutSystems.RuntimeCommon;

namespace OutSystems.HubEdition.Extensibility.Data.Platform {

    /// <summary>
    /// Represents an instance that allows full usage of the database.
    /// </summary>
    public interface IPlatformDatabaseProvider : IDatabaseProvider {

        /// <summary>
        /// Gets the <see cref="IPlatformProviderProperties"/> instance associated with this database provider.
        /// </summary>
        new IPlatformProviderProperties Properties { get; }

        /// <summary>
        /// Creates a new Empty <code>IRuntimeDatabaseConfiguration</code>
        /// </summary>
        IRuntimeDatabaseConfiguration CreateEmptyRuntimeDatabaseConfiguration();

        /// <summary>
        /// Creates a new Empty <code>IPlatformDatabaseConfiguration</code> 
        /// </summary>
        IPlatformDatabaseConfiguration CreateEmptyPlatformDatabaseConfiguration();

        /// <summary>
        /// Creates a new Empty <code>ISessionDatabaseConfiguration</code>
        /// </summary>
        ISessionDatabaseConfiguration CreateEmptySessionDatabaseConfiguration();

        /// <summary>
        /// Creates a new PlatformConfigurationManager <code>IPlatformConfigurationManager</code>
        /// </summary>
        IPlatformConfigurationManager GetConfigurationManager(IPlatformDatabaseConfiguration uiConfiguration);

        /// <summary>
        /// Creates a new SessionConfigurationManager <code>ISessionConfigurationManager</code>
        /// </summary>
        ISessionConfigurationManager GetConfigurationManager(ISessionDatabaseConfiguration uiConfiguration);

        /// <summary>
        /// Returns an instance of <code>IPlatformDatabaseServices</code> that uses the supplied configuration to access the database.
        /// </summary>
        IPlatformDatabaseServices GetPlatformDatabaseServices(IRuntimeDatabaseConfiguration databaseConfiguration);
    }
}
