/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using OutSystems.HubEdition.Extensibility.Data.DatabaseObjects;

namespace OutSystems.HubEdition.Extensibility.Data.Platform.DatabaseObjects {

    /// <summary>
    /// Contains information about a table source trigger.
    /// </summary>
    public interface IPlatformTableSourceEventTriggerInfo {

        /// <summary>
        /// Table source that owns the trigger.
        /// </summary>
        ITableSourceInfo TableSource { get; }

        /// <summary>
        /// Name that identifies the trigger.
        /// </summary>
        string Name { get; }
        
    }
}
