/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using OutSystems.HubEdition.Extensibility.Data.DatabaseObjects;

namespace OutSystems.HubEdition.Extensibility.Data.Platform.DatabaseObjects {

    /// <summary>
    /// Contains information about a data type.
    /// </summary>
    public interface IPlatformDataTypeInfo : IDataTypeInfo {

        /// <summary>
        /// Returns true if both objects represent an equivalent database data type.
        /// </summary>
        /// <param name="other">Other datatype object to compare with</param>
        /// <returns>true if the current object is equivalent to the other parameter; otherwise, false.</returns>
        bool IsEquivalent(IDataTypeInfo other);
    }
}
