/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

package outsystems.hubedition.extensibility.data.platform.session;

import java.text.*;
import java.util.*;
import outsystems.hubedition.extensibility.data.*;
import outsystems.hubedition.extensibility.data.platform.*;
import outsystems.hubedition.util.*;
import outsystems.hubedition.util.delegates.*;
import java.math.BigDecimal;



public class RepeatedInsertException extends SessionStoreException {
    public static final TypeInformation<RepeatedInsertException> TypeInfo = TypeInformation.get(RepeatedInsertException.class);
    
    public RepeatedInsertException(String message){
        super(message);
    }
    
    public RepeatedInsertException(String message, Exception e){
        super(message, e);
    }
}
