/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

namespace OutSystems.HubEdition.Extensibility.Data.DMLService {

    /// <summary>
    /// Defines a contract for generating default values for simple queries.
    /// </summary>
    public interface IDMLDefaultValues {

        /// <summary>
        /// Gets the associated DML service.
        /// </summary>
        IDMLService DMLService { get; }

        /// <summary>
        /// Gets a DML expression that returns the NULL value.
        /// </summary>
        /// <returns>DML expression</returns>
        string Null { get; }

        /// <summary>
        /// Gets a DML expression that returns the default value for Text elements.
        /// </summary>
        /// <returns>DML expression of type Text</returns>
        string Text { get; }

        /// <summary>
        /// Gets a DML expression that returns the default value for Boolean elements.
        /// </summary>
        /// <returns>DML expression of type Boolean</returns>
        string Boolean { get; }

        /// <summary>
        /// Gets a DML expression that returns the default value for Integer elements.
        /// </summary>
        /// <returns>DML expression of type Integer</returns>
        string Integer { get; }

        /// <summary>
        /// Gets a DML expression that returns the default value for Decimal elements.
        /// </summary>
        /// <returns>DML expression of type Decimal</returns>
        string Decimal { get; }

        /// <summary>
        /// Gets a DML expression that returns the default value for Date elements.
        /// </summary>
        /// <returns>DML expression of type Date</returns>
        string Date { get; }

        /// <summary>
        /// Gets a DML expression that returns the default value for Time elements.
        /// </summary>
        /// <returns>DML expression of type Time</returns>
        string Time { get; }

        /// <summary>
        /// Gets a DML expression that returns the default value for DateTime elements.
        /// </summary>
        /// <returns>DML expression of type DateTime</returns>
        string DateTime { get; }

        /// <summary>
        /// Gets a DML expression that returns the default value for BinaryData elements.
        /// </summary>
        /// <returns>DML expression of type BinaryData</returns>
        string BinaryData { get; }
    }
}
