CREATE TABLE DUMMY%Machine% (ID int NOT NULL, VAL int) ;
INSERT INTO DUMMY%Machine% (ID, VAL) VALUES (1, 1) ;
CREATE TABLE "BIG_DATA%Machine%" (ID int NOT NULL, VAL_SMALL1 varchar(50), VAL_SMALL2 varchar(50), VAL_BIG1 text, VAL_BIG2 text) ;