/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System.Reflection;

[assembly: AssemblyCompany("OutSystems")]
[assembly: AssemblyProduct("OutSystems Platform")]
[assembly: AssemblyCopyright("Copyright © OutSystems 2016")]
[assembly: AssemblyTrademark("")]

[assembly: AssemblyVersion("10.0.105.0")]
[assembly: AssemblyFileVersion("10.0.105.0")]
