CREATE TABLE "IntrospectionTestTable" (ID serial NOT NULL, DBTEXT varchar(255) NOT NULL, DBINTEGER int, DBDECIMAL decimal(37, 8), DBBOOLEAN boolean, DBDATETIME timestamp, DBBINARYDATA bytea, CONSTRAINT PK_IntrospectionTestTable PRIMARY KEY (ID));

CREATE VIEW "IntrospectionViewOverTestTable" AS SELECT * FROM "IntrospectionTestTable";

CREATE TABLE "SELECT" (TEXTID varchar(10) NOT NULL, VAL int, CONSTRAINT PK_Select PRIMARY KEY (TEXTID));

CREATE VIEW "FROM" AS SELECT * FROM "SELECT";

CREATE TABLE "ForeignKeysTable" (ID int, INTROSPECTIONID int, SELECTID varchar(10) NOT NULL);
ALTER TABLE "ForeignKeysTable" ADD CONSTRAINT FK_FKT_IntrospectionTestTable FOREIGN KEY (INTROSPECTIONID) REFERENCES "IntrospectionTestTable"(ID);
ALTER TABLE "ForeignKeysTable" ADD CONSTRAINT FK_FKT_Select FOREIGN KEY (SELECTID) REFERENCES "SELECT"(TEXTID);