/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

package outsystems.hubedition.extensibility.data;

import java.text.*;
import java.util.*;
import outsystems.hubedition.util.*;
import outsystems.hubedition.util.delegates.*;
import java.math.BigDecimal;


/**
 *	Represents a set of properties that are specific to a database provider.
 */
public interface IProviderProperties
{
    
    /**
	 *	Gets the associated IDatabaseProvider instance.
	 */
    public IDatabaseProvider getDatabaseProvider();
    
    /**
	 *	Gets the friendly name of the database provider
	 */
    public String getDisplayName();
    
    /**
	 *	Gets the friendly name of the object used to represent a database container (e.g. database, catalog, schema, ...), used  for UI generation and messages displayed to the end-user.
	 */
    public String getDatabaseContainerName();
    
    /**
	 *	Indicates if the provider's driver supports more than one active result set for a single connection.
	 */
    public boolean isSupportsMultipleActiveResultSets();
}
