/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

namespace OutSystems.HubEdition.Extensibility.Data.DMLService.DMLPlaceholders {

    /// <summary>
    /// Represents the possible placeholders for the insert SQL statement produced for the <code>Create</code> entity action.
    /// <code>{BeforeStatement} INSERT INTO Entity {BeforeValuesKeyword} VALUES (val, ... , val) {AfterStatement}</code>
    /// </summary>
    public enum InsertPlaceholder { 
        BeforeStatement,
        BeforeValuesKeyword,        
        AfterStatement 
    };

}
