/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

package outsystems.hubedition.extensibility.data.executionservice;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

public class DataColumnCollection implements Iterable<DataColumn> {

	private final List<DataColumn> columns = new ArrayList<DataColumn>();
	
	DataColumnCollection() {
	}
	
	public void add(String name, Class<?> type) {
		columns.add(new DataColumn(name, type));
	}

	@Override
	public Iterator<DataColumn> iterator() {
		return columns.iterator();
	}
	
	public int getCount() {
		return columns.size();
	}
}
