/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

package outsystems.hubedition.extensibility.data.executionservice;

public class DataTable {

	private final String tableName;
	private final DataColumnCollection columns = new DataColumnCollection();
	private final DataRowCollection rows = new DataRowCollection();
	
	public DataTable(String tableName) {
		this.tableName = tableName;
	}
	
	public String getTableName() {
		return tableName;
	}
	
	public DataColumnCollection getColumns() {
		return columns;
	}
	
	public DataRowCollection getRows() {
		return rows;
	}
	
	public DataRow getRow(int i) {
		return rows.get(i);
	}
	
	public DataRow newRow() {
		return new DataRow();
	}

}
