/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System.Data;
using OutSystems.RuntimeCommon;

namespace OutSystems.HubEdition.Extensibility.Data.ExecutionService {
    
    /// <summary>
    /// Class with extension methods to <see cref="IExecutionService"/>.
    /// </summary>
    public static class ExecutionServiceExtensions {

        ///  <summary>
        ///  Checks if a type is a date or time.
        /// <para>.NET: Returns True if a type is a DateTime, Date, or Time.</para>
        /// <para>Java: Returns True if a type if a TIMESTAMP.</para>
        ///  </summary>
        /// <param name="executionService">The execution service to use to check if a type is a date or time.</param>
        /// <param name="dbType">Type to be checked.</param>
        ///  <returns>A boolean indicating if the type is a date or time.</returns>
        public static bool IsDateType(this IExecutionService executionService, DbType dbType) {
            return (dbType == DbType.DateTime) || (dbType == DbType.Date) || (dbType == DbType.Time);
        }

        /// <summary>
        /// Checks if a type is a unicode string.
        /// <para>.NET: Returns True if a type is a String or StringFixedLength.</para>
        /// <para>Java: Returns True if a type is VARCHAR.</para>
        /// </summary>
        /// <param name="executionService">The execution service to use to check if a type is a unicode string.</param>
        /// <param name="dbType">Type to be checked.</param>
        /// <returns>A boolean indicating if the type is a unicode string.</returns>
        public static bool IsUnicodeStringType(this IExecutionService executionService, DbType dbType) {
            return (dbType == DbType.String) || (dbType == DbType.StringFixedLength);
        }
    }
}
