CREATE TABLE DUMMY (ID int NOT NULL, VAL int) ;
INSERT INTO DUMMY (ID, VAL) VALUES (1, 1) ;
CREATE TABLE "BIG_DATA" (ID int NOT NULL, VAL_SMALL1 varchar(50), VAL_SMALL2 varchar(50), VAL_BIG1 text, VAL_BIG2 text) ;
CREATE TABLE DUAL (ID int NOT NULL);
INSERT INTO DUAL (ID) VALUES (1);