/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

package outsystems.hubedition.extensibility.data.platform.databaseobjects;

import java.util.*;
import outsystems.hubedition.extensibility.data.*;
import outsystems.hubedition.extensibility.data.databaseobjects.*;
import outsystems.hubedition.extensibility.data.platform.*;
import outsystems.hubedition.util.*;
import outsystems.hubedition.util.delegates.*;
import java.math.BigDecimal;
import outsystems.hubedition.extensibility.data.databaseobjects.ITableSourceInfo;



/**
 *	Contains detailed information about a table source (data source in tabular format), like a database table or view.
 */
public interface IPlatformTableSourceInfo extends ITableSourceInfo
{
    
    /**
	 *	List of columns of the table source
	 */
    public Iterable<IPlatformTableSourceColumnInfo> getColumns();
    
    /**
	 *	List of foreign keys of the table source
	 */
    public Iterable<ITableSourceForeignKeyInfo> getForeignKeys();
    
    /**
	 *	List of indexes of the table source
	 */
    public Iterable<IPlatformTableSourceIndexInfo> getIndexes();
    
    /**
	 *	Event trigger associated with the table source, if one exists. Otherwise, returns null;
	 */
    public IPlatformTableSourceEventTriggerInfo getEventTrigger();
    
}
